dist: trusty

language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

script:
  # Fail the Travis CI build on the first error.
  - set -e
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.17.1
  - ./bin/golangci-lint run ./...
  -  go test -race -coverprofile coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
